### PR TITLE
Now all information and title tags are added.

### PR DESCRIPTION
**Pull request by NicDef**
Durch die Änderungen werden das Datum der Tabelle und der Titel zum Datensatz hinzugefügt.

### CODE REVIEW

**Comment by aschuma** [comment]
Hi @NicDef

Your proposed change may impact some of my existing automation processes. I have revised your pull request and made some adjustments. Does the updated version meet your requirements and expectations?

**Comment by NicDef** [comment]
Hello @aschuma 

Thank you for your quick reply. And yes, your adjustments meet my requirements and expectations perfectly.
Thank you very much!

**Comment by NicDef** [comment]
Hi **@aschuma**

Sorry for answering a little bit too fast. I'm just realising that there is a way to improve the data format.
My school, for example, is uploading two tables all the time. One for the present day and also one for the next. That's why I'm receiving two dates in the title. Additionally, there could be some message in the information div.

So my idea now is to create an instance containing all the tables. In this instance could be multiple instances of every single table. These nested ones could again be split into the head, information and table instance. Do you get the idea?

So the script needs to check where a table ends and then push this one with its head and information to the parent instance.

Is it OK, if I try to make these changes and send them to you?

**Comment by aschuma** [comment]
Hi @NicDef 

This service offers a simple capability of downloading HTML schedules and extracting the cells within. 

The merging of table data is beyond the scope of this project. However, I am open to incorporating the extraction of additional data, such as headers, into the code. 

Initially, I added a "flat" mode that performed some merging. This can be found in the source code at https://github.com/aschuma/dsb-untis/blob/main/src/index.js#L50. Ultimately, I decided not to include any further functionality. Instead, this can be achieved through external code. 

For instance, the code at https://github.com/aschuma/dsb-untis/blob/main/examples/extractClassData.js performs some date grouping of entries. Additionally, the code at https://github.com/aschuma/dsb-untis/blob/main/examples/extractClassData.js#L55 demonstrates how to group table rows by date.

The Units HTML format is really strange and each school has a different variation. :-(

**Comment by aschuma** [comment]
I am closing this pull request. As part of version 0.5.1, I have added the concept of "extractors", which may help you incorporate your own changes if you are using this library as a standalone tool and not within the docker image. Thank you for your valuable input.

**Pull request closed without merging**
